services:
  frontend:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.frontend
    container_name: frontend
    ports:
      - "5173:5173"
    env_file:
      - ./apps/web/.env
  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: Spoona
    volumes:
      - appData:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/Spoona?schema=public
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_started

volumes:
  appData:
