FROM node:20-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./turbo.json ./turbo.json
COPY ./apps/api ./apps/api

RUN pnpm install
RUN pnpm run build

EXPOSE 3000

CMD ["pnpm" ,"run","start:web"]