
# create base image
FROM node:22-alpine

# initialize working directory
WORKDIR /usr/src/app

# install pnpm globall
RUN npm install -g pnpm

#copy workspace configurations
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./


#copy all dependencies
COPY ./apps/api/package.json ./apps/api/
COPY ./packages/database/package.json ./packages/database/
COPY ./packages/typescript-config/package.json ./packages/typescript-config/

#install all the dependencies
RUN pnpm install

#copy the source code
COPY ./packages/database ./packages/database/
COPY ./packages/typescript-config/ ./packages/typescript-config/
COPY ./apps/api ./apps/api

# run pnpm to generate prisma client
RUN pnpm run db:generate


#expose the container port
EXPOSE 3000

#run the docker image
CMD ["pnpm" ,"run","dev:backend"]