// Most generic and commonly used diet types
export const diet = [
  "Vegetarian",
  "Non-vageterian",
  "Vegan",
  "Gluten-Free",
  "Dairy-Free",
  "Keto",
  "Paleo",
  "Low-Carb",
  "High-Protein",
  "Pescatarian",
  "Whole30",
  "Mediterranean",
  "Low-Fat",
  "Diabetic-Friendly",
  "Nut-Free",
  "Halal",
  "Kosher",
  "Low-Sodium",
  "Sugar-Free",
  "Lactose-Free",
  "Egg-Free",
  "Soy-Free",
  "Raw Food",
  "Flexitarian",
  "DASH Diet",
  "Anti-Inflammatory",
];

// Most generic and commonly used recipe categories
export const categories = [
  "Breakfast",
  "Lunch",
  "Non-vageterian",
  "Dinner",
  "Brunch",
  "Appetizers",
  "Main Course",
  "Side Dish",
  "Salads",
  "Soups",
  "Stews",
  "Desserts",
  "Beverages",
  "Snacks",
  "Baked Goods",
  "Pasta",
  "Seafood",
  "Poultry",
  "Beef",
  "Pork",
  "Lamb",
  "Vegetarian Mains",
  "Vegan Mains",
  "Sandwiches",
  "Pizza",
  "Burgers",
  "Tacos",
  "Casseroles",
  "Stir-Fry",
  "Grilled",
  "BBQ",
  "Slow Cooker",
  "Instant Pot",
  "One-Pot Meals",
  "Quick & Easy",
]

// Most generic and commonly used cuisines
export const cuisines = [
  "American",
  "Italian",
  "Mexican",
  "Chinese",
  "Japanese",
  "Indian",
  "Thai",
  "French",
  "Mediterranean",
  "Greek",
  "Spanish",
  "Middle Eastern",
  "Korean",
  "Vietnamese",
  "Caribbean",
  "Brazilian",
  "Turkish",
  "Lebanese",
  "Moroccan",
  "German",
  "British",
  "Irish",
  "African",
  "Cajun",
  "Southern",
  "Tex-Mex",
  "Asian Fusion",
  "Latin American",
  "Scandinavian",
  "Eastern European",
] 

// Type exports for TypeScript
// export type Diet = (typeof diet)[number];
// export type Category = (typeof categories)[number];
// export type Cuisine = (typeof cuisines)[number];

// export type Diet = string[];
// export type Category = string[];
// export type Cuisine = string[];